//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialsCalculator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculation
    {
        public int CalculationID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual User User { get; set; }
    }
}
